2025-01-08 14:44:59,299 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\bocha\PycharmProjects\Python_module12\tests_12_4.py", line 29, in test_run
    test_2 = Runner(6, 10)
             ^^^^^^^^^^^^^
  File "C:\Users\bocha\PycharmProjects\Python_module12\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2025-01-08 14:44:59,300 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\bocha\PycharmProjects\Python_module12\tests_12_4.py", line 19, in test_walk
    test_1 = Runner('Men1', -1)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\bocha\PycharmProjects\Python_module12\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -1
